# Site settings
title: "JaeHeon Jung"
description: >
  Home

author: JaeHeon Jung
email: lhe339@naver.com
twitter_username: 
github_username: heonyus

# Profile Information
profile_image: /assets/images/profile.jpg
location: Seoul, Republic of Korea
linkedin: honey-Jung-560ab3294
instagram: ho.en.y
followers: 19
following: 19

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heonyus.github.io" # the base hostname & protocol for your site

google_analytics_id: 
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

kramdown:
  input: GFM
  hard_wrap: true
  parse_block_html: true
  parse_span_html: true
  entity_output: as_char
  auto_ids: true
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    css_class: 'highlight'
    block:
      line_numbers: false
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols: { hellip: '...', mdash: '---', ndash: '--', laquo: '<<', raquo: '>>' }
  # GFM specific options
  gfm_quirks: []

sass:
    sass_dir: _sass
    style: compressed

exclude: 
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
